#
# Copyright(c) 2022 ZettaScale Technology and others
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License v. 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0, or the Eclipse Distribution License
# v. 1.0 which is available at
# http://www.eclipse.org/org/documents/edl-v10.php.
#
# SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause
#

trigger: none
pr: none

schedules:
- cron: "0 0 * * *"
  displayName: Midnight Refresh
  branches:
    include:
    - master

pool:
  vmImage: ubuntu-20.04

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.10'
    name: install_python
    displayName: Install Python
  - bash: |
      set -ex
      pip install poetry --user --upgrade
      poetry install
    name: install_project_deps
    displayName: Install project dependencies
  - bash: |
      set -ex
      python -m builder --commit-if-updated
    name: run_site_builder
    displayName: Run site build
  - bash: |
      set -ex
      # was-updated is written by the builder if there are updates
      if [[ -f "was-updated"]]; then
        # push builders commit
        git push
        # Let python tool handle the gh-pages sync
        ghp-import --no-jekyll --cname=cyclonedds.io --message="Azure build ${BUILD_BUILDNUMBER} for commit $(git rev-parse --verify HEAD)" --no-history --push --force --shell pages/
      fi
    name: publish
    displayName: Publish
